repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ["--verbose", "--manifest-path", "Cargo.toml", "--"]
        pass_filenames: false
      - id: cargo-check
        args: ["--manifest-path", "Cargo.toml"]
        pass_filenames: false
      - id: clippy
        args: ["--manifest-path", "Cargo.toml"]
        pass_filenames: false
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
      - id: shfmt
